- name: Creating /etc/kubernetes/manifests
  file: path=/etc/kubernetes/manifests state=directory mode=0755
- name: kube-apiserver
  template: src=kube-apiserver.yaml.j2 dest=/etc/kubernetes/manifests/kube-apiserver.yaml
