- name: loadbalancer config
  template: src=nginx.conf.j2 dest=/etc/nginx.conf
- name: loadbalancer systemd service config
  template: src=loadbalancer.service.j2 dest=/etc/systemd/system/loadbalancer.service
- name: Starting loadbalancer service
  service: name=loadbalancer state=started enabled=yes
