- name: Create /etc/kubernetes/cni
  file: path=/etc/kubernetes/cni state=directory mode=0755
- name: Create /etc/kubernetes/cni/net.d
  file: path=/etc/kubernetes/cni/net.d state=directory mode=0755
- name: Install calico conf
  template: src=10-calico.conf.j2 dest=/etc/kubernetes/cni/net.d/10-calico.conf
- name: Install calico service
  template: src=calico-node.service.j2 dest=/etc/systemd/system/calico-node.service
  notify: daemon-reload
