- name: Creating /etc/kubernetes/manifests
  file: path=/etc/kubernetes/manifests state=directory mode=0755
- name: kube-proxy
  template: src=kube-proxy.yaml.j2 dest=/etc/kubernetes/manifests/kube-proxy.yaml
